[tool.poetry]
name = "midori"
version = "0.1.0"
description = "some minecraft library downloader"
authors = ["MisileLaboratory"]
license = "MisileLab License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.7"
minecraft-launcher-lib = "5.2"
click = "8.1.3"
xmltodict = "0.13.0"

[tool.poetry.group.nvim.dependencies]
pynvim = "0.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
